app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', ['as' => 'home', function()
{
	return View::make('home');
}]);

Route::get('cart', ['as' => 'cart.index', 'uses' => 'CartController@index']);
Route::post('cart', ['as' => 'cart.store', 'uses' => 'CartController@store']);
Route::match(['put','patch'], 'cart', ['as' => 'cart.update', 'uses' => 'CartController@update']);
Route::get('checkout', ['as' => 'cart.checkout', 'uses' => 'CartController@checkout']);

Route::get('pay', [
	'as' => 'cart.pay',
	'uses' => 'CartController@sendToPaymentProcessor'
]);
Route::get('pay-success', [
	'as' => 'cart.pay-success', 
	'uses' => 'CartController@verifyWithPaymentProcessor'
]);
Route::get('pay-failure', ['as' => 'cart.pay-failure', function (){
	return Redirect::route("cart");
}]);

// TODO: change to POST

Route::resource('products', 'ProductsController');

Route::resource('users', 'UsersController');

Route::get('register', ['as' => 'register', 'uses' => 'UsersController@create']);
Route::get('login', ['as' => 'login', 'uses' => 'UsersController@login']);
Route::post('login', ['as' => 'authenticate', 'uses' => 'UsersController@authenticate']);
Route::get('logout', ['as' => 'logout', 'uses' => 'UsersController@logout']);


Route::resource('users.orders', 'UserOrderController');


Route::get('test-tx', function() {

	$purchase = Omnipay::purchase([
		'amount'        => '99.95',
		'currency'      => 'NZD',
		'EmailAddress'  => 'brett.taylor@yoobee.ac.nz',
		'transactionId' => 'banana', //uniqid(microtime()),
		'description'	=> 'lololol',
		'returnUrl'     => url('test-rx'),
		'cancelUrl'     => url('text-fail'),
	])->send();
	
	// dd($purchase);
	// return omnipay_debug($purchase);

	if ($purchase->isRedirect()) {
		return Redirect::to($purchase->getRedirectUrl());
	}

	throw new UnexpectedValueException("Payment gateway responded:\n ". $purchase->getMessage());
});

Route::get('test-rx', function (){
	//return "Success";
	$confirm = Omnipay::completePurchase([
		'result' => Input::get('result')
	])->send();
	dd($confirm);
	//return omnipay_debug($confirm);
});

Route::get('test-fail', function (){
	return "Fail.";
});

function omnipay_debug($purchase) {
	$response = new stdClass();
	$response->isSuccessful            = $purchase->isSuccessful();
	$response->isRedirect              = $purchase->isRedirect();
	$response->getMessage              = $purchase->getMessage();
	$response->getCode                 = $purchase->getCode();
	$response->getTransactionReference = $purchase->getTransactionReference();
	if ($purchase->isRedirect()) {
		$response->getRedirectUrl      = $purchase->getRedirectUrl();
		$response->getRedirectData     = $purchase->getRedirectData();
	}
	return json_encode($response);
}

// Populate layouts.master with some common variables
View::composer('layouts.master', function($view) {
	$cartCount = UserProductCart::currentUser()->cartQuantity();
	$view->with('cartCount', $cartCount);
	
	$view->with('currentUser', Auth::user());
});


App::missing(function($exception)
{
    return Response::view('errors.missing', array(), 404);
});

app/views/layouts/master.blade.php
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Shop Demo @section('page-title'):: @show</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <style>
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>
    <link rel="stylesheet" href="{{ asset('css/bootstrap-theme.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">

    <script src="{{ asset('js/vendor/modernizr-2.6.2-respond-1.1.0.min.js') }}"></script>
  </head>
  <body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    @include('layouts.nav')

    @yield('content')

    <!-- Main jumbotron for a primary marketing message or call to action -->

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset("js/vendor/jquery-1.11.0.min.js") }}"><\/script>')</script>

    <script src="{{ asset('js/vendor/bootstrap.min.js') }}"></script>

    <script src="{{ asset('js/plugins.js') }} "></script>
    <script src="{{ asset('js/main.js') }}"></script>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
      (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
      function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
      e=o.createElement(i);r=o.getElementsByTagName(i)[0];
      e.src='//www.google-analytics.com/analytics.js';
      r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
      ga('create','UA-XXXXX-X');ga('send','pageview');
    </script>
  </body>
</html>

app/views/layouts/nav.blade.php
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      {{ link_to_route('home', 'Larashop', null, ['class' => 'navbar-brand']) }}
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>{{ link_to_route('products.index', 'Products', null) }}</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ route('cart.index') }}">
          <span class="glyphicon glyphicon-shopping-cart"></span>
          Cart
          <span class="badge">{{ $cartCount }}</span>
        </a></li>
      </ul>
      @if( ! Auth::check())
        @if( Route::currentRouteName() !== 'login' && Route::currentRouteName() !== 'register' )


          {{ Form::open(
            array(
              'route' => 'login',
              'class' => 'navbar-form navbar-right',
              'role' => 'form'
            )
          ) }}
            <div class="form-group">
              {{ Form::text('email', NULL, array(
                'class' => 'form-control',
                'placeholder' => 'Email'
              )) }}
            </div>
            <div class="form-group">
              {{ Form::password('password', array(
                'class' => 'form-control',
                'placeholder' => 'Password'
              )) }}
            </div>
            {{ Form::submit('Login', array('class' => 'btn btn-success')) }}
            {{ link_to_route('register', 'Register', null, ['class' => 'btn btn-default']) }}
          {{ Form::close() }}
        
        @endif

      @else

        <div class="navbar-form navbar-right">
          {{ link_to_route('logout', "Logout", NULL, array(
            'class' => 'btn btn-default'
          )) }}
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="#">{{ Auth::user()->email }}</a>
          </li>
        </ul>

      @endif
    </div><!--/.navbar-collapse -->
  </div>
</div>